name: sse_client
description: An SSE event transformer and client for Dart applications.
version: 1.0.0
repository: https://github.com/andyhorn/sse_client

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.5.0

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
