name: simple_sse_workspace
description: A workspace for simple_sse and simple_sse_http packages.
repository: https://github.com/andyhorn/sse_client

publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - packages/simple_sse
  - packages/simple_sse_http
  - packages/simple_sse_dio
  
packages:
  - packages/*

command:
  bootstrap:
    runPubGetInParallel: true

melos:
  scripts:
    analyze: melos exec -- dart analyze .
    format: melos exec -- dart format .
    test: melos exec -- dart test .
    publish:dry: melos exec -- dart pub publish --dry-run

dev_dependencies:
  melos: ^7.3.0
