name: simple_sse
description: An SSE event transformer for simplified SSE client implementations.
version: 2.0.0
repository: https://github.com/andyhorn/sse_client
resolution: workspace

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
