name: simple_sse_http
description: An implementation of the `SseClient` interface using the `http` package.
version: 1.0.0
repository: https://github.com/andyhorn/sse_client
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
