name: simple_sse_dio
description: An implementation of the `SseClient` interface using the `dio` package.
version: 1.0.0
repository: https://github.com/andyhorn/sse_client
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  simple_sse: ^2.0.0
  dio: ^5.9.0

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
